### PR TITLE
Added feature to support disabled elements inside the select

### PR DESCRIPTION
**Pull request by peterhorvathbim**
Elements can now be disabled. 
If the items has no `isDisbled` attribute sepcified, or `isDisabled=true` it will not disable the element, otherwise, if `isDisabled=true` it disables it. ( Visual upgrade + not clickable )

### CODE REVIEW

**Comment by tregusti** [comment]
Eric, you take this away. And release a new version.

But next time, no version bumps within the PR. There might be more things to release than this PR.

**Comment by ericpitcher** [comment]
> @ericpitcher, you take this away. And release a new version.
> 
> But next time, no version bumps within the PR. There might be more things to release than this PR.

@tregusti take away and release new version as in reverting the commit that bumps the version, merging the PR and then release?

**Comment by tregusti** [comment]
Nah, just merge. Then tag the merge commit as 3.2.0. yarn publish and push.

If I remember correctly...

If it works, add something to readme. Something along these lines:

https://github.com/bimobject/bim-select/pull/13#discussion-diff-263097245L3

**Comment by ericpitcher** [comment]
@tregusti 

When I do ```yarn publish``` it wants the username and password to npm, which I don't have. Doesn't this get published to myget though? Can't find anything mentioning myget in the repo

**Comment by tregusti** [comment]
Ahh, no. bim-select is publicly hosted on github since it’s publicly installable with `yarn add bim-select`.

My bad, only I have currently access to publish it to the npm registry. Give me your username on npmjs.org and you will get access to publish it as well. Since it’s owned by BIMobject it’s only fair =)

**Comment by tregusti** [comment]
Ahh, no. bin-select is publicly hosted on github since it’s publicly
installable with yarn add bim-select.

My bad, only I have currently access to publish it. Give me your username
on npmjs.org and you will get access to publish it as well. Since it’s
owned by BIMobject it’s only fair =)


On 12 March 2019 at 15:34:51, Eric Pitcher (notifications@github.com) wrote:

@tregusti <https://github.com/tregusti>

When I do yarn publish it wants the username and password to npm, which I
don't have. Doesn't this get published to myget though? Can't find anything
mentioning myget in the repo

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/bimobject/bim-select/pull/14#issuecomment-472025913>,
or mute the thread

**Comment by ericpitcher** [comment]
@tregusti eric.bim is my username. Thanks mate!

**Comment by tregusti** [comment]
Added.

You should be able to publish now. Use `npm publish` and not `yarn publish` to publish, since `yarn` want to bump the version... Personal choice.

**Comment by ericpitcher** [comment]
@tregusti after publishing the new version to npm the prepublish script runs ```yarn build```, I end up with new files in the dist directory. I remember you saying something about why the dist directory is checked into source control, I guess the same repo is used for distribution of the built files. But aren't those new files in the dist dir supposed to be in the same commit as the v3.2.0 tag?

**Comment by tregusti** [comment]
it runs `yarn build` to verify that it _can_ build. That no errors occur. Sanity check.

If the files in `build` differ, then either the src files differ, or the path to the repo differs (stupid thing, but webpack uses the full path to the file as an identifier, so if built in two different folders or on different machines, the dist files will differ).

And regarding when to push, you are correct, I was wrong in https://github.com/bimobject/bim-select/pull/13#discussion-diff-263097245L3. Tag the release in git AFTER a successful publish since that is when you know that the release was successful. But if all went well with the publish, a tag before the publish is not a problem.

Follow?

Otherwise, lets have a lunch tomorrow =)

**Comment by ericpitcher** [comment]
@tregusti 

Yes I follow, then I should be fine how it is now. Thanks for the help! Lunch would be cool to do anyways!

**Pull request merged**
